# Generated by Django 3.2.4 on 2021-07-11 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate', models.IntegerField(choices=[(8055, 'captain'), (7611, 'lieutenant'), (7309, 'seat_1'), (7131, 'seat_2'), (6714, 'seat_3'), (6419, 'seat_4'), (6070, 'seat_5'), (5890, 'seat_6'), (5552, 'seat_7'), (5540, 'seat_8'), (5241, 'seat_9'), (5136, 'seat_10'), (4946, 'seat_11'), (4172, 'seat_12'), (4136, 'seat_13'), (3502, 'seat_14'), (2747, 'seat_15'), (2303, 'seat_16'), (1943, 'seat_17'), (1733, 'seat_18')], default=1733, validators=[django.core.validators.MaxValueValidator(limit_value=8055), django.core.validators.MinValueValidator(limit_value=1733)])),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_wages', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('clock_id', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
                ('position', models.ManyToManyField(to='employees.Position')),
            ],
        ),
    ]
