[package]
name = "rust"
version = "0.1.0"
authors = ["wearypossum4770 <wearypossum4770@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
num-traits = "0.2"
itertools = "0.10.0"
ferris-says = "0.2"
