pub mod add_binary;
pub mod addition;
pub mod baseball_points;
pub mod binary_search;
pub mod calc_age;
pub mod calculator;
pub mod circuit_power;
pub mod concat_string;
pub mod count_points;
pub mod generation;
pub mod get_first_value;
pub mod get_vote_count;
pub mod give_me_something;
pub mod hello;
pub mod less_than100;
pub mod less_than_or_equal_to_zero;
pub mod next_integer;
pub mod polygon_angle_sum;
pub mod rectangle_perimeter;
pub mod remainder;
pub mod search_insert;
pub mod tri_area;
pub mod triangle_inequality_theorem;
pub mod count_farm_legs;
pub mod hours_and_minutes_to_seconds;
pub mod football_points;
// pub mod remove_element;
// pub mod roman_to_int;
// pub mod minutes_to_seconds;
