from django.contrib.auth import get_user_model

from users.models import Profile

data = [
    {
        "password": "pbkdf2_sha256$260000$Yx1va4WiGQfxYAd380yzDZ$yAreZ3kbR/hFF6gz0UnbFRxbOG+aYLkeUaueu/dDHiw=",
        "username": "orihime_inoue",
        "email": "orihime_inoue@human.com",
        "date_joined": "2021-07-06T02:01:52.641Z",
        "madien_name": "Inoue",
        "first_name": "Orihime",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1991-09-03",
        "date_of_death": None,
    },
    {
        "_id": 81,
        "password": "pbkdf2_sha256$260000$MZk5cYr4u8TxDdG86H7RFI$iB/98hTVxiPZHh+PY4QeE7rJtu3wPFRvBZwVfYKs4Y4=",
        "username": "ichigo.kurosaki",
        "email": "ichigo.kurosaki@soul.society.com",
        "date_joined": "2021-06-02T20:00:50.420Z",
        "madien_name": None,
        "first_name": "Ichigo",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1991-07-15",
        "date_of_death": None,
    },
    {
        "_id": 132,
        "password": "pbkdf2_sha256$260000$CRYCfKp4jkHMJDRQsXaKNF$hREkB5DNdOd1sQYHigz/V/MeIpqUpJil5Ji61LoICz0=",
        "username": "isshin_kurosaki",
        "email": "isshin_kurosaki@shinigami.com",
        "date_joined": "2021-07-06T02:01:13.560Z",
        "madien_name": None,
        "first_name": "Isshin",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1971-12-10",
        "date_of_death": None,
    },
    {
        "_id": 260,
        "password": "pbkdf2_sha256$260000$vwj1b5WyRCG2vMFdsXtdy9$hbmXw9NJAd4sQjEg4ehnDEgLIGgPDhTcGAVsM8IwJqQ=",
        "username": "masaki_kurosaki",
        "email": "masaki_kurosaki@quincy.com",
        "date_joined": "2021-07-06T02:01:45.582Z",
        "madien_name": None,
        "first_name": "Masaki",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1971-06-09",
        "date_of_death": "2021-06-08",
    },
    {
        "_id": 296,
        "password": "pbkdf2_sha256$260000$8GeX2H1gPYCRTmVhWNX9tj$FixQjonDpg9f+6nOY6vXfeu948Gg6U7CLUX/QP00bYA=",
        "username": "karin_kurosaki",
        "email": "karin_kurosaki@human.com",
        "date_joined": "2021-07-06T02:01:54.275Z",
        "madien_name": None,
        "first_name": "Karin",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": None,
        "date_of_death": None,
    },
    {
        "_id": 297,
        "password": "pbkdf2_sha256$260000$RcRkfIXA3qUrAPL4tTEhpq$+SRhk3bUpgrt32RFWchPlpoKsEDR1sjW3hN4rxvytns=",
        "username": "yuzu_kurosaki",
        "email": "yuzu_kurosaki@human.com",
        "date_joined": "2021-07-06T02:01:54.540Z",
        "madien_name": None,
        "first_name": "Yuzu",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1996-05-06",
        "date_of_death": None,
    },
    {
        "_id": 297,
        "password": "pbkdf2_sha256$260000$RcRkfIXA3qUrAPL4tTEhpq$+SRhk3bUpgrt32RFWchPlpoKsEDR1sjW3hN4rxvytns=",
        "username": "kazui_kurosaki",
        "email": "kazui_kurosaki@human.com",
        "date_joined": "2021-07-06T02:01:54.540Z",
        "madien_name": None,
        "first_name": "Kazui",
        "last_name": "Kurosaki",
        "middle_name": None,
        "date_of_birth": "1996-05-06",
        "date_of_death": None,
    },
]
