[package]
name = "toml"
version = "0.4.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
homepage  = "www.example.com"
description =  "a really cool app"
[scripts]

[[repository.heroku]]
url = ""
repo_name = "heroku_app"
keysfile= ""
default_run = "" # a unix chron string.
auto_publish = false
[[repository.github]]
default_run = "" # a unix chron string.
auto_publish = false
[[repository.gitlab]]
default_run = "" # a unix chron string.
auto_publish = false
[profile.dev]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false  
[profile.staging]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false  
[profile.production]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false  
[database]
[servers]
[servers.alpha]
ip = "10.0.0.1"
role = "frontend"
