name: BUN CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  continue: true
  time: 3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
      - name: Run script
        run: bun index.js
