name: BUN CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  continue: true
  time: 3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun Runtime
        run: curl https://bun.sh/install | bash
      - name: Set Bun Completions
        run: bun completions
      - name: run tests
        run: bun wiptest