name: BUN CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  continue: true
  time: 3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun Runtime
        sh: curl https://bun.sh/install | bash && export BUN_INSTALL="/home/runner/.bun" && export PATH="$BUN_INSTALL/bin:$PATH && bun --version && exit 0
        run: echo "$PATH"
        # && bun completions && bun wiptest
