name: BUN CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  continue: true
  time: 3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BUN Runtime
        uses: antongolub/action-setup-bun@v1
      - name: BUN tests
        run: bun wiptest
on:
  push:
    branches: ["MGOD-"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        # You may pin to the exact commit or the version.
        # uses: atlassian/gajira-login@90a599561baaf8c05b080645ed73db7391c246ed
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
          string:  '^MGOD-\d*' #${{ github.event.ref }}
      # - name: Jira Issue Transition
      # You may pin to the exact commit or the version.
      # uses: atlassian/gajira-transition@0fb280dcc874710a4ac5eced8789e1def040e35d
      # uses: atlassian/gajira-transition@v2.0.2
      # with:
      #   # Key of the issue to be transitioned
      #   issue:
      #   # The transition to apply to the issue, e.g. 'In Progress'
      #   transition: # optional
      #   # The id of a transition to apply to the issue
      #   transitionId: # optional
